sudo: required
services:
    - docker

before_install:
    - docker build -t dpartap/react-app -f Dockerfile.dev ./client

script:
    - docker run -e CI=true dpartap/react-app npm run test

deploy:
    provider: elasticbeanstalk
    region:  "us-east-2"
    app: "react-app"
    env: "ReactApp-env"
    bucket_name: "elasticbeanstalk-us-east-2-334266025345"
    bucket_path: "react-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_ID
    secret_access_key: $AWS_SECRET_KEY
